apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: {{cluster_name}}
  region: {{region_name}}

nodeGroups:
  - name: group1
    instanceType: t3a.large
    minSize: 0
    maxSize: 6
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        imageBuilder: true
        xRay: true
        cloudWatch: true
