#!/bin/bash

# this script assumes the name of the EKS cluster is vinobank
# please modify the following files if the cluster name is different
#    cluster.yaml
#    aws-load-balancer-controller-v2_4_1_full.yaml
#

CLUSTER_NAME=vinobank
CLUSTER_REGION=us-west-2

COUNT=$(eksctl get cluster -o json | jq ".[].Name" | grep -c $CLUSTER_NAME)

if [ $COUNT -eq 0 ]; then

  echo creating new cluster $CLUSTER_NAME in $CLUSTER_REGION
  sleep 5

  sed 's/{{cluster_name}}/'${CLUSTER_NAME}'/;s/{{region_name}}/'${CLUSTER_REGION}'/' cluster.yaml | eksctl create cluster -f - 
  sleep 5
  aws eks --region $CLUSTER_REGION update-kubeconfig --name $CLUSTER_NAME

else

  echo Cluster $CLUSTER_NAME already exists...

fi

ClusterName=$CLUSTER_NAME
LogRegion=$CLUSTER_REGION
FluentBitHttpPort='2020'
FluentBitReadFromHead='Off'
[[ ${FluentBitReadFromHead} = 'On' ]] && FluentBitReadFromTail='Off'|| FluentBitReadFromTail='On'
[[ -z ${FluentBitHttpPort} ]] && FluentBitHttpServer='Off' || FluentBitHttpServer='On'
curl -s https://raw.githubusercontent.com/aws-samples/amazon-cloudwatch-container-insights/latest/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/quickstart/cwagent-fluent-bit-quickstart.yaml | sed 's/{{cluster_name}}/'${ClusterName}'/;s/{{region_name}}/'${LogRegion}'/;s/{{http_server_toggle}}/"'${FluentBitHttpServer}'"/;s/{{http_server_port}}/"'${FluentBitHttpPort}'"/;s/{{read_from_head}}/"'${FluentBitReadFromHead}'"/;s/{{read_from_tail}}/"'${FluentBitReadFromTail}'"/' | kubectl apply -f - 
curl -s https://raw.githubusercontent.com/aws-observability/aws-otel-collector/main/deployment-template/eks/otel-container-insights-infra.yaml | kubectl apply -f -
sleep 25

kubectl get pods -l name=aws-otel-eks-ci -n aws-otel-eks
