apiVersion: apps/v1
kind: Deployment
metadata:
  name: fund-transfer
  labels:
    app: fund-transfer
spec:
  selector:
    matchLabels:
      app: fund-transfer
  template:
    metadata:
      labels:
        app: fund-transfer
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: docker.io/sloppycoder/vinobank-fund-transfer:1.0.1-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-cred
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-cred
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-cred
                  key: AWS_DEFAULT_REGION
            - name: OLTP_COLLECTOR_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 5            
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 5            
            periodSeconds: 10
          resources:
            requests:
              cpu: 500m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 512Mi
      
---
apiVersion: v1
kind: Service
metadata:
  namespace: vinobank
  name: fund-transfer
  labels:
    app: fund-transfer
spec:
  type: LoadBalancer
  selector:
    app: fund-transfer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

---
# disable ingress for now
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: fund-transfer
#   annotations:
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
#     alb.ingress.kubernetes.io/ssl-redirect: '443'
#     alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:211281185885:certificate/567ffc9e-a592-4345-8724-be2d81a525a5
#     alb.ingress.kubernetes.io/auth-type: oidc
#     alb.ingress.kubernetes.io/auth-scope: openid
#     alb.ingress.kubernetes.io/auth-session-timeout: '3600'
#     alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
#     alb.ingress.kubernetes.io/auth-on-unauthenticated-request: deny
# spec:
#   ingressClassName: alb
#   rules:
#     - http:
#         paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             service:
#               name: fund-transfer
#               port:
#                 number: 8080

